apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/devspaces.openshift-operators: ""
  name: devspaces
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  channel: stable
  installPlanApproval: Automatic
  name: devspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: devspacesoperator.v3.7.0